FROM ubuntu:16.04

RUN apt-get update
RUN apt-get install -y sudo
RUN sudo apt-get install -y python
RUN sudo apt-get install -y ssh
RUN sudo apt-get install -y net-tools

RUN sudo useradd -ms /bin/bash {<user_id>}

COPY ./authorized_keys /home/{<user_id>}/.ssh/
COPY ./docker_bootstrap_script.sh	 /home/{<user_id>}/
COPY ./myOverrides	 /etc/sudoers.d/

RUN sudo chown {<user_id>}:{<user_id>} /home/{<user_id>}/.ssh/*

WORKDIR /home/{<user_id>}
